version: '3'
services:
  dc-full-stack-code-challenge-api:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    command: uvicorn main:app --reload
    network_mode: host
